name: datapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
    
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  provider: ^6.1.5
  fl_chart: ^1.0.0
  shared_preferences: ^2.1.1

dependency_overrides:
  flutter_map: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
